### ISSUE TITLE
Question about Calibration params between radar coordinate to camera coordinate 

### ISSUE THREAD

**Issue by Egozjuer** [jgiroux8/T_FFTRadNet#1]
Hello,in the example_laser_projection.ipynb, I only found the rotation_vector and translation_vector from laser lidar to camera coordiante,but how to get the relationship from radar coordinate to camera coordinate?

**Comment by jgiroux8** [comment]
Hello,

Sorry for such a late reply.
For this information, I would direct you to the ValeoAI github linked in the README.
